// Run with: bun src/_gen_pokemon_thumbs.ts > src/lib/pokemonThumbs.ts
// Generates pokemonThumbs.ts with base64 PNG thumbnails for each variant.
import { createCanvas } from "canvas";
import { drawPokemonThumb } from "./lib/pokemonScene";
import { POKEMON_VARIANTS } from "./lib/pokemon";

const SIZE = 64;
const lines: string[] = [
  "// AUTO-GENERATED by _gen_pokemon_thumbs.ts — do not edit by hand.",
  "export const POKEMON_THUMBS: Record<string, string> = {",
];

for (const variant of POKEMON_VARIANTS) {
  const canvas = createCanvas(SIZE, SIZE);
  const ctx = canvas.getContext("2d");
  drawPokemonThumb(ctx as never, variant, SIZE);
  const b64 = canvas.toDataURL("image/png");
  lines.push(`  "${variant}": "${b64}",`);
}

lines.push("};");
console.log(lines.join("\n"));
