// Run with: bun src/_gen_spiderman_thumbs.ts > src/lib/spidermanThumbs.ts
// Generates spidermanThumbs.ts with base64 PNG thumbnails for each variant.
import { createCanvas } from "canvas";
import { drawSpidermanThumb } from "./lib/spidermanScene";
import { SPIDERMAN_VARIANTS } from "./lib/spiderman";

const SIZE = 64;
const lines: string[] = [
  "// AUTO-GENERATED by _gen_spiderman_thumbs.ts — do not edit by hand.",
  "export const SPIDERMAN_THUMBS: Record<string, string> = {",
];

for (const variant of SPIDERMAN_VARIANTS) {
  const canvas = createCanvas(SIZE, SIZE);
  const ctx = canvas.getContext("2d");
  drawSpidermanThumb(ctx as never, variant, SIZE);
  const b64 = canvas.toDataURL("image/png");
  lines.push(`  "${variant}": "${b64}",`);
}

lines.push("};");
console.log(lines.join("\n"));
