// Run with: bun src/_gen_got_thumbs.ts
// Generates gotThumbs.ts with base64 PNG thumbnails for each variant.
import { createCanvas } from "canvas";
import { drawGotThumb } from "./lib/gotScene";
import { GAMEOFTHRONES_VARIANTS } from "./lib/gameofthrones";

const SIZE = 64;
const lines: string[] = [
  "// AUTO-GENERATED by _gen_got_thumbs.ts — do not edit by hand.",
  "export const GOT_THUMBS: Record<string, string> = {",
];

for (const variant of GAMEOFTHRONES_VARIANTS) {
  const canvas = createCanvas(SIZE, SIZE);
  const ctx = canvas.getContext("2d");
  drawGotThumb(ctx as never, variant, SIZE);
  const b64 = canvas.toDataURL("image/png");
  lines.push(`  "${variant}": "${b64}",`);
}

lines.push("};");
console.log(lines.join("\n"));
