// Run with: bun src/_gen_ironman_thumbs.ts
// Generates ironmanThumbs.ts with base64 PNG thumbnails for each variant.
import { createCanvas } from "canvas";
import { drawIronmanCell, IRONMAN_VARIANTS } from "./lib/ironman";

const SIZE = 64;
const lines: string[] = [
  "// AUTO-GENERATED by _gen_ironman_thumbs.ts — do not edit by hand.",
  "// Tiny pixel-art helmet previews for the Iron Man theme sub-options, rendered",
  "// from src/lib/ironman.ts so they always match the real wallpaper output.",
  "export const IRONMAN_THUMBS: Record<string, string> = {",
];

for (const variant of IRONMAN_VARIANTS) {
  const canvas = createCanvas(SIZE, SIZE);
  const ctx = canvas.getContext("2d");
  ctx.antialias = "none";
  if (variant === "mixed") {
    // The Hall of Armor tile shows all four levels of the mixed progression
    // in a 2×2 grid (Mk I → Mk II → Mk III → Mk LXXXV).
    const h = SIZE / 2;
    drawIronmanCell(ctx as never, 0, 0, h, 0, "mixed", 0);
    drawIronmanCell(ctx as never, h, 0, h, 1, "mixed", 0);
    drawIronmanCell(ctx as never, 0, h, h, 2, "mixed", 0);
    drawIronmanCell(ctx as never, h, h, h, 3, "mixed", 0);
  } else {
    drawIronmanCell(ctx as never, 0, 0, SIZE, 3, variant, 0);
  }
  const b64 = canvas.toDataURL("image/png");
  lines.push(`  "${variant}": "${b64}",`);
}

lines.push("};");
console.log(lines.join("\n"));
